-- =====================================================================
-- Project Part IV - Application and Governance Extension
-- Target: PostgreSQL 16
--
-- Part IV reuses the 36 tables created in Parts II and III. Only two
-- kinds of change are made here, and both are required for the
-- end-to-end application to run:
--
--   1. ML_CLUSTER_INDICATOR_MAP
--      The governed bridge between a reviewed ML cluster and an existing
--      HEALTH_INDICATOR. Without it there is no controlled path from
--      model output to business context, and an unreviewed cluster could
--      only be surfaced raw or not at all.
--
--   2. Identity sequences on four Part II key columns.
--      CONTRACT, CONTRACT_BENEFIT, CONTRACT_PREMIUM, and DATA_ASSET were
--      loaded from curated CSV files with externally supplied keys, so
--      their primary keys have no default. The Part IV application
--      inserts into all four at run time. Attaching a sequence is a
--      physical change only: column types, constraints, and existing
--      rows are untouched.
--
-- The script is idempotent and can be re-applied.
-- =====================================================================

\echo 'Applying Part IV extension...'

-- ---------------------------------------------------------------------
-- 1. ML_CLUSTER_INDICATOR_MAP
--
-- Governance chain enforced by this table:
--     ML cluster  ->  human interpretation  ->  HEALTH_INDICATOR
--                 ->  HEALTH_OBSERVATION    ->  account geography
--                 ->  quote research context
--
-- A row here is an assertion by a named analyst that a discovered
-- document theme corresponds to a specific structured indicator already
-- present in the ODS. The application shows a mapped theme as an
-- approved insight only when the row is active AND the underlying
-- ML_CLUSTER_SUMMARY has HumanReviewed = TRUE. Two independent gates,
-- because a mapping created before review must never become visible if
-- the review is later withheld.
--
-- The composite foreign key to ML_CLUSTER_SUMMARY means a mapping cannot
-- reference a cluster that does not exist in that run, and a deleted run
-- takes its mappings with it.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ML_CLUSTER_INDICATOR_MAP (
    MLClusterIndicatorMapID BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MLRunID                 BIGINT       NOT NULL,
    ClusterID               INTEGER      NOT NULL,
    HealthIndicatorID       INTEGER      NOT NULL REFERENCES HEALTH_INDICATOR (IndicatorID),
    ApprovedBy              VARCHAR(100) NOT NULL,
    ApprovedAt              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ReviewNotes             VARCHAR(500),
    IsActive                BOOLEAN      NOT NULL DEFAULT TRUE,
    CreatedAt               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_mcim_cluster FOREIGN KEY (MLRunID, ClusterID)
        REFERENCES ML_CLUSTER_SUMMARY (MLRunID, ClusterID) ON DELETE CASCADE,
    -- An approval with no named approver is not an approval.
    CONSTRAINT ck_mcim_approver CHECK (length(trim(ApprovedBy)) > 0),
    -- One active mapping per cluster/indicator pair. Re-approving the
    -- same pair updates the existing row instead of stacking duplicates.
    CONSTRAINT uq_mcim_active UNIQUE (MLRunID, ClusterID, HealthIndicatorID)
);
COMMENT ON TABLE ML_CLUSTER_INDICATOR_MAP IS
    'Governed link from a human-reviewed ML cluster to an existing HEALTH_INDICATOR. Decision support only: never an input to pricing or eligibility.';
COMMENT ON COLUMN ML_CLUSTER_INDICATOR_MAP.ApprovedBy IS
    'Named analyst accountable for the interpretation. Required.';
COMMENT ON COLUMN ML_CLUSTER_INDICATOR_MAP.IsActive IS
    'FALSE retires a mapping without deleting the audit record.';

-- Access path: "which approved indicators belong to the active run".
CREATE INDEX IF NOT EXISTS ix_mcim_run_active
    ON ML_CLUSTER_INDICATOR_MAP (MLRunID, IsActive);

-- Access path: "which themes point at this indicator", used when the
-- quote page walks from a regional observation back to a model theme.
CREATE INDEX IF NOT EXISTS ix_mcim_indicator
    ON ML_CLUSTER_INDICATOR_MAP (HealthIndicatorID) WHERE IsActive;

-- ---------------------------------------------------------------------
-- 2. Identity sequences for application inserts.
--
-- setval starts each sequence above the highest key already loaded, so
-- the application never collides with curated data.
-- ---------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS contract_contractid_seq         AS BIGINT;
CREATE SEQUENCE IF NOT EXISTS contract_benefit_benefitid_seq  AS BIGINT;
CREATE SEQUENCE IF NOT EXISTS contract_premium_premiumid_seq  AS BIGINT;
CREATE SEQUENCE IF NOT EXISTS data_asset_assetid_seq          AS BIGINT;

SELECT setval('contract_contractid_seq',
              COALESCE((SELECT max(ContractID) FROM CONTRACT), 0) + 1, false);
SELECT setval('contract_benefit_benefitid_seq',
              COALESCE((SELECT max(BenefitID) FROM CONTRACT_BENEFIT), 0) + 1, false);
SELECT setval('contract_premium_premiumid_seq',
              COALESCE((SELECT max(PremiumID) FROM CONTRACT_PREMIUM), 0) + 1, false);
SELECT setval('data_asset_assetid_seq',
              COALESCE((SELECT max(AssetID) FROM DATA_ASSET), 0) + 1, false);

ALTER TABLE CONTRACT         ALTER COLUMN ContractID SET DEFAULT nextval('contract_contractid_seq');
ALTER TABLE CONTRACT_BENEFIT ALTER COLUMN BenefitID  SET DEFAULT nextval('contract_benefit_benefitid_seq');
ALTER TABLE CONTRACT_PREMIUM ALTER COLUMN PremiumID  SET DEFAULT nextval('contract_premium_premiumid_seq');
ALTER TABLE DATA_ASSET       ALTER COLUMN AssetID    SET DEFAULT nextval('data_asset_assetid_seq');

ALTER SEQUENCE contract_contractid_seq        OWNED BY CONTRACT.ContractID;
ALTER SEQUENCE contract_benefit_benefitid_seq OWNED BY CONTRACT_BENEFIT.BenefitID;
ALTER SEQUENCE contract_premium_premiumid_seq OWNED BY CONTRACT_PREMIUM.PremiumID;
ALTER SEQUENCE data_asset_assetid_seq         OWNED BY DATA_ASSET.AssetID;

-- ---------------------------------------------------------------------
-- 2b. Label the existing DS010 asset as version 1.
--
-- Part II and Part III had one unstructured source and no need for a
-- version label. Part IV appends a new DATA_ASSET row every time the
-- source changes, so the original needs a label to be comparable with
-- its successors.
-- ---------------------------------------------------------------------
UPDATE DATA_ASSET
   SET SchemaVersion = 'v1'
 WHERE DatasetID = 'DS010'
   AND AssetType = 'unstructured document'
   AND COALESCE(NULLIF(TRIM(SchemaVersion), ''), '') = '';

-- ---------------------------------------------------------------------
-- 3. Supporting indexes for the Part IV application workload.
--
-- Both are added because the application reads these paths on every
-- dashboard and quote-detail request, not because a plan looked slow in
-- the abstract. Measurements are in part4/evidence/query_performance.csv.
-- ---------------------------------------------------------------------

-- Dashboard: quotes grouped and filtered by status, newest first.
CREATE INDEX IF NOT EXISTS ix_quote_status_created
    ON QUOTE (QuoteStatus, CreatedAt DESC);

-- Quote detail: the status trail for one quote in chronological order.
CREATE INDEX IF NOT EXISTS ix_qsh_quote_changed
    ON QUOTE_STATUS_HISTORY (QuoteID, ChangedAt);

-- ---------------------------------------------------------------------
-- 4. Application role.
--
-- Least privilege: the application role reads and writes business data
-- but cannot alter structure. Part III already created ml_service_role
-- and analyst_role; this adds the application's own identity.
-- Password is intentionally not set here. It is granted out of band by
-- the operator; no credential is stored in version control.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'part4_app_role') THEN
        CREATE ROLE part4_app_role NOLOGIN;
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO part4_app_role;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO part4_app_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO part4_app_role;
-- No DELETE, no DDL. Quote and contract history is append-only in this
-- application; corrections are new rows, never silent removals.
REVOKE DELETE ON ALL TABLES IN SCHEMA public FROM part4_app_role;

\echo 'Part IV extension applied.'
