-- =====================================================================
-- Project Part III - ML Metadata and Result Extension
-- Target: PostgreSQL 16
--
-- Stores model governance information and clustering results for the
-- DS010 unstructured document analysis.
--
-- DESIGN DECISIONS
--  1. DOCUMENT_CHUNK references the existing DATA_ASSET row for DS010.
--     No second document catalogue is created.
--  2. The PDF binary is NOT stored in PostgreSQL. It stays in the data
--     lake raw zone. The database holds metadata, checksum, relative
--     path, extracted text, model output, and lineage only.
--  3. Configuration and metrics are stored as JSONB so a model run is
--     reproducible from the database alone without a fixed column set.
-- =====================================================================

\echo 'Creating Part III ML metadata extension...'

-- ---------------------------------------------------------------------
-- ML_RUN - one row per training execution.
-- This is the model governance record: what ran, on what, with which
-- seed, and what it scored.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ML_RUN (
    MLRunID           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModelName         VARCHAR(100) NOT NULL,
    ModelVersion      VARCHAR(20)  NOT NULL,
    Algorithm         VARCHAR(50)  NOT NULL,
    ConfigurationJSON JSONB        NOT NULL,
    RandomSeed        INTEGER      NOT NULL,
    TrainingDatasetID VARCHAR(10)  REFERENCES DATASET (DatasetID),
    StartedAt         TIMESTAMPTZ  NOT NULL,
    CompletedAt       TIMESTAMPTZ,
    Status            VARCHAR(20)  NOT NULL DEFAULT 'Running',
    MetricsJSON       JSONB,
    CONSTRAINT ck_mlrun_status CHECK (Status IN ('Running','Completed','Failed')),
    CONSTRAINT ck_mlrun_times CHECK (CompletedAt IS NULL OR StartedAt <= CompletedAt),
    CONSTRAINT uq_mlrun_name_version UNIQUE (ModelName, ModelVersion)
);
COMMENT ON TABLE ML_RUN IS
    'Model governance record: one row per training run with config, seed, and metrics for reproducibility.';

-- ---------------------------------------------------------------------
-- DOCUMENT_CHUNK - the analysis units extracted from an unstructured
-- asset. DataAssetID ties every chunk back to the physical file in the
-- data lake, which ties back to DATASET for source and licence.
--
-- ChunkChecksum lets a later run detect whether the extracted text
-- changed, which is how re-extraction drift is caught.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNK (
    DocumentChunkID BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DataAssetID     INTEGER      NOT NULL REFERENCES DATA_ASSET (AssetID),
    PageNumber      INTEGER      NOT NULL,
    SectionName     VARCHAR(200),
    ChunkText       TEXT         NOT NULL,
    WordCount       INTEGER      NOT NULL,
    ChunkChecksum   CHAR(64)     NOT NULL,
    CreatedAt       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_chunk_page CHECK (PageNumber >= 1),
    CONSTRAINT ck_chunk_words CHECK (WordCount > 0),
    CONSTRAINT uq_chunk_checksum UNIQUE (DataAssetID, ChunkChecksum)
);
COMMENT ON TABLE DOCUMENT_CHUNK IS
    'Text chunks extracted from an unstructured DATA_ASSET. Page number preserved for traceability. PDF binary stays in the data lake.';

-- ---------------------------------------------------------------------
-- ML_CLUSTER_RESULT - one row per chunk per run.
-- Composite primary key: a chunk gets exactly one cluster per run.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ML_CLUSTER_RESULT (
    MLRunID            BIGINT        NOT NULL REFERENCES ML_RUN (MLRunID) ON DELETE CASCADE,
    DocumentChunkID    BIGINT        NOT NULL REFERENCES DOCUMENT_CHUNK (DocumentChunkID),
    ClusterID          INTEGER       NOT NULL,
    DistanceToCentroid NUMERIC(12,6),
    RelativeScore      NUMERIC(8,6),
    CreatedAt          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (MLRunID, DocumentChunkID),
    CONSTRAINT ck_mlcr_cluster CHECK (ClusterID >= 0),
    CONSTRAINT ck_mlcr_distance CHECK (DistanceToCentroid IS NULL OR DistanceToCentroid >= 0)
);
COMMENT ON TABLE ML_CLUSTER_RESULT IS
    'Cluster assignment for each document chunk in a model run.';

-- ---------------------------------------------------------------------
-- ML_CLUSTER_SUMMARY - the interpreted output.
--
-- HumanReviewed is the governance gate. A cluster interpretation is not
-- approved for business use until a person has reviewed it and set this
-- flag. The report and any downstream use must respect that.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ML_CLUSTER_SUMMARY (
    MLRunID                 BIGINT       NOT NULL REFERENCES ML_RUN (MLRunID) ON DELETE CASCADE,
    ClusterID               INTEGER      NOT NULL,
    ClusterLabel            VARCHAR(200),
    TopTermsJSON            JSONB,
    RepresentativeChunksJSON JSONB,
    BusinessInterpretation  TEXT,
    HumanReviewed           BOOLEAN      NOT NULL DEFAULT FALSE,
    ReviewedAt              TIMESTAMPTZ,
    ReviewedBy              VARCHAR(100),
    PRIMARY KEY (MLRunID, ClusterID),
    CONSTRAINT ck_mlcs_cluster CHECK (ClusterID >= 0),
    -- A review timestamp without the flag, or a flag without a reviewer,
    -- would make the governance record meaningless.
    CONSTRAINT ck_mlcs_review CHECK (
        (HumanReviewed = FALSE AND ReviewedAt IS NULL AND ReviewedBy IS NULL)
        OR (HumanReviewed = TRUE AND ReviewedAt IS NOT NULL AND ReviewedBy IS NOT NULL))
);
COMMENT ON TABLE ML_CLUSTER_SUMMARY IS
    'Interpreted cluster output. HumanReviewed must be TRUE with a reviewer before business use.';

\echo 'Part III ML metadata extension created.'
